### ISSUE TITLE
Oddity in composer.json regarding PHP version

### ISSUE THREAD

**Issue by chaziz94** [chazizsquarebracket/squarebracket#10]
```
"config": {
	"platform": {
		"php": "7.3"
		}
	}
```

I found this weird oddity in the composer.json file. 7.3 is losing support in 7 months, and the production server is using 8.0, not 7.3.

**Comment by chaziz94** [comment]
@forkiesassds hold on which version of PHP is production running. Was it 8.0?

**Comment by rollerozxa** [comment]
It's for resolving Composer dependencies independently of the current PHP version that it's running under. I put it at 7.3 when I first made the `composer.json` because that is the latest PHP version available for stable Debian, but I think you can safely increase it to 8.0 since production runs it and we all develop on 8.0.

**Comment by chaziz94** [comment]
well my testing environment still uses 7.4(?) because I haven't updated XAMPP since the VERY VERY early poktube days, though I'll just edit the composer file.
